#! /bin/sh

export PATH="$PATH:~/configs/gui/.config/sxhkd/"

redshift -x && redshift -O 3000

killall sxhkd
sxhkd > /tmp/sxhkd.log &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           1
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_unplugged_monitors  true
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true
bspc config focus_follows_pointer      false
